#pragma once

#define PRINT         1
#define IF            2
#define ELSE          3
#define ELIF          4
#define WHILE         5
#define FOR           6
#define END           7
#define TINT          8
#define TREAL         9
#define SEMICOLON     10
#define OPARENTHESIS  11
#define CPARENTHESIS  12
#define OBRACKET      13
#define CBRACKET      14
#define COLON         15
#define NEGATION      16
#define ATRIBUITION   17
#define SUM           18
#define SUBTRACT      19
#define MULTIPLY      20
#define DIVIDE        21
#define POW           22
#define MODULUS       23
#define CPRODUCT      24
#define SPRODUCT      25
#define TMATRIX       26
#define IMATRIX       27
#define EQ            28
#define NE            29
#define GT            30
#define GE            31
#define LT            32
#define LE            33
#define INCREMENT     34
#define DECREMENT     35
#define NONE          36
#define SPACE         37
#define NLINE         38
#define ID            39
#define INTEGER       40
#define REAL          41
#define ERROR         42
#define OCBRACKET     43
#define CCBRACKET     44
#define TRUE          45
#define FALSE         46
#define AND           47
#define OR            48
